name: Atualização Diária de Tips
on:
  schedule:
    - cron: '0 12 * * *' # Roda todo dia às 12:00 UTC (09:00 Brasília)
  workflow_dispatch: # Permite rodar manualmente se quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Rodar script de atualização
        run: python update_tips.py

      - name: Salvar mudanças no site
        run: |
          git config --global user.name 'Bot de Tips'
          git config --global user.email 'bot@tips.com'
          git add .
          git commit -m "Atualização automática de tips" || exit 0
          git push
